org: neelgajjar004
service: serverless-student-portal
frameworkVersion: '3'

provider: 
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage,'dev'}
  memorySize: 512
  timeout: 30
  layers:
    - !Ref NodeModuleLibsLambdaLayer
  environment:
    USER_POOL: !Ref CognitoUserPool
    USER_POOL_CLIENT: !Ref CognitoUserPoolClient
    USER_TABLE: !Ref UserTable
    SUPER_ADMIN_GROUP: SuperAdmin
    FACULTY_GROUP: Faculty
    STUDENT_GROUP: Student
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:SignUp
        - cognito-idp:ConfirmSignUp
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:InitiateAuth
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminDeleteUser
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt UserTable.Arn
        - !Join [ "/", [ !GetAtt UserTable.Arn, "*" ] ]
        # - !GetAtt StudentTable.Arn
        # - !Join [ "/", [ !GetAtt StudentTable.Arn, "*" ] ]

custom:
  userPoolName: ${self:service}-UserPool-${opt:stage, self:provider.stage}
  userPoolClientName: ${self:service}-UserPoolClient-${opt:stage, self:provider.stage}
  userTableName: userTable-${opt:stage, self:provider.stage}  
  # studentTableName: studentTable-${opt:stage, self:provider.stage}

package:
  individually: true

layers:
  NodeModuleLibs:
      path: layers 

functions:
  register:
    handler: functions/auth/register.handler
    description: "Serverless-Student-Portal : Register a New User"
    events:
      - http:
          path: register
          method: post
          cors: true
    package:
      include:
        - functions/auth/register.mjs
        - utils/**
      exclude:
        - "**/*"
  confirm-register:
    handler: functions/auth/confirm-register.handler
    description: "Serverless-Student-Portal : Confirm Register a New User"
    events:
      - http:
          path: verifyRegister
          method: post
          cors: true
    package:
      include:
        - functions/auth/confirm-register.mjs
        - utils/**
      exclude:
        - "**/*"
  login:
    handler: functions/auth/login.handler
    description: "Serverless-Student-Portal : Login User"
    events:
      - http:
          path: login
          method: post
          cors: true
    package:
      include:
        - functions/auth/login.mjs
        - utils/**
      exclude:
        - "**/*"
  logout:
    handler: functions/auth/logout.handler
    description: "Serverless-Student-Portal : Logout User"
    events:
      - http:
          path: logout
          method: post
          cors: true
    package:
      include:
        - functions/auth/logout.mjs
        - utils/**
      exclude:
        - "**/*"
  create-faculty:
    handler: functions/faculty/create-faculty.handler
    description: "Serverless-Student-Portal : SuperAdmin & Faculty User Can Create a New Faculty User"
    events:
      - http:
          path: faculty
          method: post
          cors: true
          authorizer:
            name: FacultyAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/faculty/create-faculty.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  create-student:
    handler: functions/student/create-student.handler
    description: "Serverless-Student-Portal : Faculty Can Create a New Student"
    events:
      - http:
          path: students
          method: post
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/student/create-student.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  update-student:
    handler: functions/student/update-student.handler
    description: "Serverless-Student-Portal : Faculty Can update a Existing Students"
    events:
      - http:
          path: students/{studentId}
          method: put
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/student/update-student.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  student-list:
    handler: functions/student/student-list.handler
    description: "Serverless-Student-Portal : Faculty Can Listing a Existing Students"
    events:
      - http:
          path: students
          method: get
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/student/student-list.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  user-details:
    handler: functions/users/user-details.handler
    description: "Serverless-Student-Portal : User Details"
    events:
      - http:
          path: users/me
          method: get
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/users/user-details.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  delete-user:
    handler: functions/users/user-delete.handler
    description: "Serverless-Student-Portal : Delete User "
    events:
      - http:
          path: users/{userId}
          method: delete
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/users/user-delete.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"
  user-list:
    handler: functions/users/user-list.handler
    description: "Serverless-Student-Portal : User List "
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer:
            name: StudentAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
    package:
      include:
        - functions/users/user-list.mjs
        - utils/**
        - middlewares/**
      exclude:
        - "**/*"

resources:
  Resources:
    CognitoUserPool: ${file(resources/cognito/cognito-userpool.yml)}
    
    CognitoUserPoolClient: ${file(resources/cognito/cognito-userpool-client.yml)}

    SuperAdminGroup: ${file(resources/cognito-group/superAdmin-cognito-group.yml)}
    
    FacultyGroup: ${file(resources/cognito-group/faculty-cognito-group.yml)}

    StudentGroup: ${file(resources/cognito-group/student-cognito-group.yml)}

    UserTable: ${file(resources/dynamoDB/dynamodb-user-table.yml)}

    # StudentTable: ${file(resources/dynamoDB/dynamodb-student-table.yml)}
    