org: neelgajjar004
service: serverless-student-portal
frameworkVersion: '3'

provider: 
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage,'dev'}
  memorySize: 512
  timeout: 30
  environment:
    USER_TABLE: ${self:custom.userTableName}
    STUDENT_TABLE: ${self:custom.studentTableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt UserTable.Arn
        - !Join [ "/", [ !GetAtt UserTable.Arn, "*" ] ]
        - !GetAtt StudentTable.Arn
        - !Join [ "/", [ !GetAtt StudentTable.Arn, "*" ] ]

        
# plugins:
#   - serverless-offline
  # - serverless-dotenv-plugin

custom:
  userTableName: userTable-${opt:stage, self:provider.stage}  
  studentTableName: studentTable-${opt:stage, self:provider.stage}  

functions:
  createUser:
    handler: user/create-user.handler
    description: "Serverless-Student-Portal : Create a New User"
    events:
      - http:
          path: user
          method: post
          cors: true


resources:
  Resources:
    UserTable: ${file(resources/dynamoDB/dynamodb-user-table.yml)}
    
    StudentTable: ${file(resources/dynamoDB/dynamodb-student-table.yml)}

    CognitoUserPool: ${file(resources/cognito/cognito-userpool.yml)}

    CognitoUserPoolClient: ${file(resources/cognito/cognito-userpool-client.yml)}


    